import docx
from docx.oxml import parse_xml

OMML_EQUATIONS = {
    '1': '<m:oMath xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math"><m:sSub><m:e><m:r><m:t>R</m:t></m:r></m:e><m:sub><m:r><m:t>t→t+h, c</m:t></m:r></m:sub></m:sSub><m:r><m:t> = ln(</m:t></m:r><m:sSub><m:e><m:r><m:t>P</m:t></m:r></m:e><m:sub><m:r><m:t>t+h, c</m:t></m:r></m:sub></m:sSub><m:r><m:t>) − ln(</m:t></m:r><m:sSub><m:e><m:r><m:t>P</m:t></m:r></m:e><m:sub><m:r><m:t>t, c</m:t></m:r></m:sub></m:sSub><m:r><m:t>)</m:t></m:r></m:oMath>',
    '2': '<m:oMath xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math"><m:sSub><m:e><m:r><m:t>P̂</m:t></m:r></m:e><m:sub><m:r><m:t>t+h, c</m:t></m:r></m:sub></m:sSub><m:r><m:t> = </m:t></m:r><m:sSub><m:e><m:r><m:t>P</m:t></m:r></m:e><m:sub><m:r><m:t>t, c</m:t></m:r></m:sub></m:sSub><m:r><m:t> · exp(</m:t></m:r><m:sSub><m:e><m:r><m:t>R̂</m:t></m:r></m:e><m:sub><m:r><m:t>t→t+h, c</m:t></m:r></m:sub></m:sSub><m:r><m:t>)</m:t></m:r></m:oMath>',
    '3': '<m:oMath xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math"><m:sSub><m:e><m:r><m:t>out</m:t></m:r></m:e><m:sub><m:r><m:t>k</m:t></m:r></m:sub></m:sSub><m:r><m:t> = ReLU(</m:t></m:r><m:sSub><m:e><m:r><m:t>Conv1D</m:t></m:r></m:e><m:sub><m:r><m:t>k</m:t></m:r></m:sub></m:sSub><m:r><m:t>(</m:t></m:r><m:sSup><m:e><m:r><m:t>x</m:t></m:r></m:e><m:sup><m:r><m:t>CNN</m:t></m:r></m:sup></m:sSup><m:r><m:t>)),   k ∈ {3, 7, 15}</m:t></m:r></m:oMath>',
    '4': '<m:oMath xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math"><m:sSub><m:e><m:r><m:t>f</m:t></m:r></m:e><m:sub><m:r><m:t>CNN</m:t></m:r></m:sub></m:sSub><m:r><m:t> = TemporalAttention(LayerNorm(Proj(Concat(</m:t></m:r><m:sSub><m:e><m:r><m:t>out</m:t></m:r></m:e><m:sub><m:r><m:t>3</m:t></m:r></m:sub></m:sSub><m:r><m:t>, </m:t></m:r><m:sSub><m:e><m:r><m:t>out</m:t></m:r></m:e><m:sub><m:r><m:t>7</m:t></m:r></m:sub></m:sSub><m:r><m:t>, </m:t></m:r><m:sSub><m:e><m:r><m:t>out</m:t></m:r></m:e><m:sub><m:r><m:t>15</m:t></m:r></m:sub></m:sSub><m:r><m:t>))))</m:t></m:r></m:oMath>',
    '5': '<m:oMath xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math"><m:sSub><m:e><m:r><m:t>h</m:t></m:r></m:e><m:sub><m:r><m:t>t</m:t></m:r></m:sub></m:sSub><m:r><m:t> = GRU(</m:t></m:r><m:sSubSup><m:e><m:r><m:t>x</m:t></m:r></m:e><m:sub><m:r><m:t>t</m:t></m:r></m:sub><m:sup><m:r><m:t>GRU</m:t></m:r></m:sup></m:sSubSup><m:r><m:t>, </m:t></m:r><m:sSub><m:e><m:r><m:t>h</m:t></m:r></m:e><m:sub><m:r><m:t>t-1</m:t></m:r></m:sub></m:sSub><m:r><m:t>),   </m:t></m:r><m:sSub><m:e><m:r><m:t>f</m:t></m:r></m:e><m:sub><m:r><m:t>GRU</m:t></m:r></m:sub></m:sSub><m:r><m:t> = </m:t></m:r><m:sSub><m:e><m:r><m:t>h</m:t></m:r></m:e><m:sub><m:r><m:t>L</m:t></m:r></m:sub></m:sSub><m:r><m:t> ∈ </m:t></m:r><m:sSup><m:e><m:r><m:t>ℝ</m:t></m:r></m:e><m:sup><m:r><m:t>d</m:t></m:r></m:sup></m:sSup></m:oMath>',
    '6': '<m:oMath xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math"><m:r><m:t>z = </m:t></m:r><m:f><m:num><m:sSup><m:e><m:r><m:t>x</m:t></m:r></m:e><m:sup><m:r><m:t>KAN</m:t></m:r></m:sup></m:sSup><m:r><m:t> − t</m:t></m:r></m:num><m:den><m:r><m:t>|s| + </m:t></m:r><m:sSup><m:e><m:r><m:t>10</m:t></m:r></m:e><m:sup><m:r><m:t>-4</m:t></m:r></m:sup></m:sSup></m:den></m:f><m:r><m:t>,   ψ(z) = (1 − </m:t></m:r><m:sSup><m:e><m:r><m:t>z</m:t></m:r></m:e><m:sup><m:r><m:t>2</m:t></m:r></m:sup></m:sSup><m:r><m:t>) · </m:t></m:r><m:sSup><m:e><m:r><m:t>e</m:t></m:r></m:e><m:sup><m:r><m:t>−0.5z²</m:t></m:r></m:sup></m:sSup></m:oMath>',
    '7': '<m:oMath xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math"><m:sSub><m:e><m:r><m:t>f</m:t></m:r></m:e><m:sub><m:r><m:t>KAN</m:t></m:r></m:sub></m:sSub><m:r><m:t> = LayerNorm(Proj(Concat(ReLU(</m:t></m:r><m:sSub><m:e><m:r><m:t>W</m:t></m:r></m:e><m:sub><m:r><m:t>lin</m:t></m:r></m:sub></m:sSub><m:sSup><m:e><m:r><m:t>x</m:t></m:r></m:e><m:sup><m:r><m:t>KAN</m:t></m:r></m:sup></m:sSup><m:r><m:t>), ReLU(</m:t></m:r><m:sSub><m:e><m:r><m:t>W</m:t></m:r></m:e><m:sub><m:r><m:t>wav</m:t></m:r></m:sub></m:sSub><m:r><m:t>ψ(z))))))</m:t></m:r></m:oMath>',
    '8': '<m:oMath xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math"><m:sSub><m:e><m:r><m:t>g</m:t></m:r></m:e><m:sub><m:r><m:t>h</m:t></m:r></m:sub></m:sSub><m:r><m:t> = MLP([</m:t></m:r><m:sSub><m:e><m:r><m:t>f</m:t></m:r></m:e><m:sub><m:r><m:t>CNN</m:t></m:r></m:sub></m:sSub><m:r><m:t> ‖ </m:t></m:r><m:sSub><m:e><m:r><m:t>f</m:t></m:r></m:e><m:sub><m:r><m:t>GRU</m:t></m:r></m:sub></m:sSub><m:r><m:t> ‖ </m:t></m:r><m:sSub><m:e><m:r><m:t>f</m:t></m:r></m:e><m:sub><m:r><m:t>KAN</m:t></m:r></m:sub></m:sSub><m:r><m:t> ‖ </m:t></m:r><m:sSub><m:e><m:r><m:t>Pos</m:t></m:r></m:e><m:sub><m:r><m:t>h</m:t></m:r></m:sub></m:sSub><m:r><m:t> ‖ </m:t></m:r><m:sSub><m:e><m:r><m:t>x</m:t></m:r></m:e><m:sub><m:r><m:t>ctx</m:t></m:r></m:sub></m:sSub><m:r><m:t>])</m:t></m:r></m:oMath>',
    '9': '<m:oMath xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math"><m:sSub><m:e><m:r><m:t>w</m:t></m:r></m:e><m:sub><m:r><m:t>h</m:t></m:r></m:sub></m:sSub><m:r><m:t> = Softmax(</m:t></m:r><m:sSub><m:e><m:r><m:t>g</m:t></m:r></m:e><m:sub><m:r><m:t>h</m:t></m:r></m:sub></m:sSub><m:r><m:t>) = [</m:t></m:r><m:sSub><m:e><m:r><m:t>w</m:t></m:r></m:e><m:sub><m:r><m:t>1</m:t></m:r></m:sub></m:sSub><m:r><m:t>, </m:t></m:r><m:sSub><m:e><m:r><m:t>w</m:t></m:r></m:e><m:sub><m:r><m:t>2</m:t></m:r></m:sub></m:sSub><m:r><m:t>, </m:t></m:r><m:sSub><m:e><m:r><m:t>w</m:t></m:r></m:e><m:sub><m:r><m:t>3</m:t></m:r></m:sub></m:sSub><m:sSup><m:e><m:r><m:t>]</m:t></m:r></m:e><m:sup><m:r><m:t>T</m:t></m:r></m:sup></m:sSup><m:r><m:t>,   </m:t></m:r><m:sSubSup><m:e><m:r><m:t>∑</m:t></m:r></m:e><m:sub><m:r><m:t>i=1</m:t></m:r></m:sub><m:sup><m:r><m:t>3</m:t></m:r></m:sup></m:sSubSup><m:sSub><m:e><m:r><m:t>w</m:t></m:r></m:e><m:sub><m:r><m:t>i</m:t></m:r></m:sub></m:sSub><m:r><m:t> = 1</m:t></m:r></m:oMath>',
    '10': '<m:oMath xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math"><m:sSub><m:e><m:r><m:t>f</m:t></m:r></m:e><m:sub><m:r><m:t>fused</m:t></m:r></m:sub></m:sSub><m:r><m:t> = </m:t></m:r><m:sSub><m:e><m:r><m:t>w</m:t></m:r></m:e><m:sub><m:r><m:t>1</m:t></m:r></m:sub></m:sSub><m:sSub><m:e><m:r><m:t>f</m:t></m:r></m:e><m:sub><m:r><m:t>CNN</m:t></m:r></m:sub></m:sSub><m:r><m:t> + </m:t></m:r><m:sSub><m:e><m:r><m:t>w</m:t></m:r></m:e><m:sub><m:r><m:t>2</m:t></m:r></m:sub></m:sSub><m:sSub><m:e><m:r><m:t>f</m:t></m:r></m:e><m:sub><m:r><m:t>GRU</m:t></m:r></m:sub></m:sSub><m:r><m:t> + </m:t></m:r><m:sSub><m:e><m:r><m:t>w</m:t></m:r></m:e><m:sub><m:r><m:t>3</m:t></m:r></m:sub></m:sSub><m:sSub><m:e><m:r><m:t>f</m:t></m:r></m:e><m:sub><m:r><m:t>KAN</m:t></m:r></m:sub></m:sSub><m:r><m:t> ∈ </m:t></m:r><m:sSup><m:e><m:r><m:t>ℝ</m:t></m:r></m:e><m:sup><m:r><m:t>d</m:t></m:r></m:sup></m:sSup></m:oMath>',
    '11': '<m:oMath xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math"><m:sSubSup><m:e><m:r><m:t>ŷ</m:t></m:r></m:e><m:sub><m:r><m:t>t+h, c</m:t></m:r></m:sub><m:sup><m:r><m:t>(q)</m:t></m:r></m:sup></m:sSubSup><m:r><m:t> = </m:t></m:r><m:sSub><m:e><m:r><m:t>Head</m:t></m:r></m:e><m:sub><m:r><m:t>q</m:t></m:r></m:sub></m:sSub><m:r><m:t>(</m:t></m:r><m:sSub><m:e><m:r><m:t>f</m:t></m:r></m:e><m:sub><m:r><m:t>fused</m:t></m:r></m:sub></m:sSub><m:r><m:t>) + </m:t></m:r><m:sSub><m:e><m:r><m:t>γ</m:t></m:r></m:e><m:sub><m:r><m:t>h</m:t></m:r></m:sub></m:sSub><m:r><m:t> · </m:t></m:r><m:sSubSup><m:e><m:r><m:t>x</m:t></m:r></m:e><m:sub><m:r><m:t>t, c</m:t></m:r></m:sub><m:sup><m:r><m:t>target</m:t></m:r></m:sup></m:sSubSup></m:oMath>',
    '12': '<m:oMath xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math"><m:sSub><m:e><m:r><m:t>ℒ</m:t></m:r></m:e><m:sub><m:r><m:t>total</m:t></m:r></m:sub></m:sSub><m:r><m:t> = </m:t></m:r><m:sSub><m:e><m:r><m:t>ℒ</m:t></m:r></m:e><m:sub><m:r><m:t>pinball</m:t></m:r></m:sub></m:sSub><m:r><m:t> + α · </m:t></m:r><m:sSub><m:e><m:r><m:t>ℒ</m:t></m:r></m:e><m:sub><m:r><m:t>balance</m:t></m:r></m:sub></m:sSub></m:oMath>',
    '13': '<m:oMath xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math"><m:sSub><m:e><m:r><m:t>ℒ</m:t></m:r></m:e><m:sub><m:r><m:t>pinball</m:t></m:r></m:sub></m:sSub><m:r><m:t> = </m:t></m:r><m:f><m:num><m:r><m:t>1</m:t></m:r></m:num><m:den><m:r><m:t>C · H · |𝒬|</m:t></m:r></m:den></m:f><m:sSub><m:e><m:r><m:t>∑</m:t></m:r></m:e><m:sub><m:r><m:t>c,h,q</m:t></m:r></m:sub></m:sSub><m:r><m:t> max(q(y − </m:t></m:r><m:sSup><m:e><m:r><m:t>ŷ</m:t></m:r></m:e><m:sup><m:r><m:t>(q)</m:t></m:r></m:sup></m:sSup><m:r><m:t>), (q−1)(y − </m:t></m:r><m:sSup><m:e><m:r><m:t>ŷ</m:t></m:r></m:e><m:sup><m:r><m:t>(q)</m:t></m:r></m:sup></m:sSup><m:r><m:t>))</m:t></m:r></m:oMath>',
    '14': '<m:oMath xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math"><m:sSub><m:e><m:r><m:t>ℒ</m:t></m:r></m:e><m:sub><m:r><m:t>balance</m:t></m:r></m:sub></m:sSub><m:r><m:t> = </m:t></m:r><m:sSubSup><m:e><m:r><m:t>∑</m:t></m:r></m:e><m:sub><m:r><m:t>i=1</m:t></m:r></m:sub><m:sup><m:r><m:t>3</m:t></m:r></m:sup></m:sSubSup><m:r><m:t> (</m:t></m:r><m:sSub><m:e><m:r><m:t>w̄</m:t></m:r></m:e><m:sub><m:r><m:t>i</m:t></m:r></m:sub></m:sSub><m:r><m:t> − </m:t></m:r><m:f><m:num><m:r><m:t>1</m:t></m:r></m:num><m:den><m:r><m:t>3</m:t></m:r></m:den></m:f><m:sSup><m:e><m:r><m:t>)</m:t></m:r></m:e><m:sup><m:r><m:t>2</m:t></m:r></m:sup></m:sSup><m:r><m:t>,   α = 0.01</m:t></m:r></m:oMath>'
}

doc = docx.Document()
for k, omml in OMML_EQUATIONS.items():
    p = doc.add_paragraph()
    p.add_run(f"Eq {k}: ")
    p._p.append(parse_xml(omml))

doc.save("test_omml_clean.docx")
print("Saved test_omml_clean.docx successfully!")
